name: the_country_number_widgets
description: A small widgets library for flutter for entering phone numbers with null safety (consider using version 0.9.0 to skip null safety)
version: 0.9.3
homepage: https://github.com/ondbyte/the_country_number_widgets

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  the_country_number: ^0.9.2+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:

  assets:
    - country_flags/
