name: the_country_number_widgets
description: A small widgets library for flutter for entering phone numbers with null safety (consider using version 0.9.0 to skip null safety)
version: 0.9.1
homepage: https://github.com/ondbyte/the_country_number_widgets

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  the_country_number: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - country_flags/
